name: Destroy clevercloud demo application on feature branch deletion

on:
  delete:
    branches:
      - feature/*

env:
  application-name: 'my-app'
  # Should be either 'personal' or 'organisation'
  deployment-owner-type: 'personal'

jobs:
  get-deleted-branch-ref:
    runs-on: ubuntu-latest
    outputs:
      deleted-branch-ref: ${{ steps.deleted-branch-ref.outputs.branch-ref }}
    steps:
      - name: Get the deleted branch reference without the 'feature/' prefix
        id: deleted-branch-ref
        run: echo "::set-output name=branch-ref::$(echo ${{ github.event.ref }} | cut -d'/' -f 2)"

  destroy-deployed-application:
    needs:
      - get-deleted-branch-ref
    uses: ./.github/workflows/_remove-application.clevercloud.reusable.yml
    with:
      application-full-slug: ${{ format('{0}-{1}', env.application-name, needs.get-deleted-branch-ref.outputs.deleted-branch-ref) }}
      deployment-owner-type: ${{ env.deployment-owner-type }}
